### ISSUE TITLE
numpy.load problem

### ISSUE THREAD

**Issue by limitime** [hellochick/ICNet-tensorflow#1]
when i try to use your code,it reports that a byte  is not in range 128 when using numpy.load to decode model file.I think it may be the python version accounting for this.could you tell me your py and tensorflow version?

**Comment by hellochick** [comment]
Hey @limitime, I am using python 2.7 & tensorflow 1.3. If you are using python 3.5, you can try specify decode parameter:
```
np.load(file, encoding = 'latin1')
```
If this could solve your problem, just tell me. I will fix this bug, thanks!

**Comment by limitime** [comment]
Hey @hellochick ,I have tried 'latin1','bytes' and numpy.mm.load() which uses cpickle method,but none of them worked.Today I establish an environment of your version and I successfully get my results! I am sorry that I don't know if there is a methond to handle this without changing py version.Besides,I also want to see your train codes,and it will do great benefit to me.I would be very thankful if you provide them.

**Comment by hellochick** [comment]
Hey @limitime, I will provide the training code. But since the origin author of ICNet did not provide the training code, I could only take a guess at what he did and try to write the training code. I will do my best.

**Comment by limitime** [comment]
@hellochick Never mind,you have done a great job.
