### ISSUE TITLE
Old repo vs new one (download ADE20K weights)

### ISSUE THREAD

**Issue by aliericcantona** [hellochick/ICNet-tensorflow#104]
Hi, first the 
python script/download_weights.py --dataset ade20k

gives me this error. 
 from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError

Also, looking at the previous code, where do we load the weights?  "Strangely" by pass this line in inference.py "if args.model == 'others': and I was still be able to run on my images. Do we manually set the weights in the model.py?
Because I don't have any of .npy files.

**Comment by joyce39** [comment]
Did you find a solution for getting the npy files for the de20k dataset?
