### ISSUE TITLE
 Dimension 0 in both shapes must be equal, but are 21 and 19. Shapes are [21] and [19]. for 'conv6_cls_2/Assign' (op: 'Assign') with input shapes: [21], [19].

### ISSUE THREAD

**Issue by caijh23** [hellochick/ICNet-tensorflow#108]
I cannot train with my own dataset using the pretrained model icnet_cityscapes_train_30k_bnnomerge.npy

**Comment by songshan0321** [comment]
How did u solve it? 
I get the same error even after doing this:
```restore_var = [v for v in tf.global_variables() if 'conv6_cls' not in v.name]```
