### ISSUE TITLE
ValueError: Shape must be rank 4 but is rank 3 for 'data_sub2' (op: 'ResizeBilinear') with input shapes: [720,720,3], [2].

### ISSUE THREAD

**Issue by helingjiao2025** [hellochick/ICNet-tensorflow#110]
Hi hellochick, when I was training on ADE20K, I got this problem: ValueError: Shape must be rank 4 but is rank 3 for 'data_sub2' (op: 'ResizeBilinear') with input shapes: [720,720,3], [2].
curiously, I can evaluate and inference this. What happend? thank u

**Comment by helingjiao2025** [comment]
it's my fault.

**Comment by ym641925331** [comment]
How can solve it

**Comment by helingjiao2025** [comment]
This problem has happened for a long time. I have forgotten the specific reason.
Maybe it's because of the TensorFlow version.

maybe you can try this:

in /utils/ image_reader.py

           #dataset = dataset.batch(cfg.BATCH_SIZE, drop_remainder=True)
           dataset = dataset.batch(cfg.BATCH_SIZE)
hope it can help you


在2019-11-28 11:58:53，ym641925331notifications@github.com写道：

How can solve it
