### ISSUE TITLE
image size for training

### ISSUE THREAD

**Issue by manuel-88** [hellochick/ICNet-tensorflow#16]
Hey,
what image size do I need for training the model to get the best inference results on the cityscapes test images? When I use INPUT_SIZE =  '1024,2048' I can only do a BATCH_SIZE = 8 to get the data into GPU memory. 

Is it better to train with smaller images and than just upscale?

thanks in advance

**Comment by hellochick** [comment]
Hey @manuel-88 , I think training with high resolution as you can is much better.

**Comment by ifangcheng** [comment]
When the image size in my own dataset is small (e.g. 80 *120),   when I train the model, how should I  set  INPUT_SIZE?
INPUT_SIZE='720,720'
INPUT_SIZE='480,480'
or it should be:
INPUT_SIZE='80,120'      ?
