### ISSUE TITLE
About the evaluation result

### ISSUE THREAD

**Issue by YiSyuanChen** [hellochick/ICNet-tensorflow#17]
Hello,
First I want to thank you for your great job. I have some problems when using evaluate.py. As you mentioned on README, I downloaded the Cityscape dataset. However, the annotation file name is end with "labelIds.png" instead of "labelTrainIds.png". Thus I just generated a new eval_list.txt based on yours. The final evaluation mIoU is only about 0.006. I am not quite sure where is the mistake. Do I miss something? Any comments will be much appreciated.

**Comment by hellochick** [comment]
@YiSyuanChen , you can refer to this issue #10

**Comment by YiSyuanChen** [comment]
@hellochick  OH!! I am sorry for asking same question, and really thanks for your help.

**Comment by hellochick** [comment]
@YiSyuanChen , thats okay. Please feel free to let me know if you have any questions!
