### ISSUE TITLE
How to convert layer BN and interp?

### ISSUE THREAD

**Issue by flyingmrwang** [hellochick/ICNet-tensorflow#22]
There should be two layers, BN and Interp, which cannot be directly converted with the tool. Could you please provide some details for translating model from caffe to tensorflow?

**Comment by hellochick** [comment]
Hey, I convert the model by handcraft. To deal with BN layer, I use `tf.layers.batch_normalization` and get update keys using `tf.get_collection(tf.GraphKeys.UPDATE_OPS)` ( you can see this line in train.py ). For interpolation layer, I use simple resize function `tf.image.resize_bilinear`.

**Comment by flyingmrwang** [comment]
Thanks for your reply~ I am actually trying to implement ICNet on caffe2. But the model translator failed to recognize BN and interp, which is no surprise....
