### ISSUE TITLE
a ValueError raised when  training 

### ISSUE THREAD

**Issue by lizilongcn** [hellochick/ICNet-tensorflow#27]
Hi，I'm a newcomer on TensorFlow and Machine Learning. When I run the file "train.py", I encountered a problem, and I have no idea how to solve it. Could you help me on this  problem ?Thanks 

```
ValueError: Dimension 3 in both shapes must be equal, but are 27 and 19 for 'conv6_cls_1/Assign' (op: 'Assign') with input shapes: [1,1,128,27], [1,1,128,19].
```

**Comment by hellochick** [comment]
Hey, @lizilongcn this results from mismatch of `NUM_CLASSES` variable, and this is my fault. You can re-clone the codes, I have fixed it! Thank you.

**Comment by lizilongcn** [comment]
Wow，Thank you for your prompt reply！ The problem is solved~
