### ISSUE TITLE
JPG image size error

### ISSUE THREAD

**Issue by ifangcheng** [hellochick/ICNet-tensorflow#3]
I try to inference my own .jpg images with different sizes (e.g. 312*492  264*385  1435*832),   i got invalidargument error like this:
 (inputs to operation sub12_sum of type AddN must have the same size and shape. input 0: [1，128，256，128]!=input 1: [1，49，33，128]) 

it seems that the code did have preprocess to resize the input image size to 1024*2048，so i got confused.

**Comment by ifangcheng** [comment]
I sucessfully run inference.py with the default  input image given in the input folder.
however,  when I try to inference my own .jpg images with different sizes (e.g. 312*492, 264*385 ,1435*832), i got invalidargument error like this:
(inputs to operation sub12_sum of type AddN must have the same size and shape. input 0: [1，128，256，128]!=input 1: [1，49，33，128])

it seems that the code did have preprocess to resize the input image size to 1024*2048，so i got confused.

**Comment by hellochick** [comment]
Hey @ifangcheng , Sorry for that it seems this network still have some input size problem, and it can only run with 1024x2048 input image ( Since original network is designed for cityscapes dataset ). I will try to fix and improve it.

**Comment by ifangcheng** [comment]
thanks for the quick response!
looking forward to your nice job!

**Comment by hellochick** [comment]
@ifangcheng , Hey, I have fixed the problem, you can update the repo and try!

**Comment by ifangcheng** [comment]
@hellochick，yes! it works now! nice job!
I will test the model‘s performance in terms of accuracy and speed!

**Comment by ifangcheng** [comment]
today, I tried a much smaller size image (e.g. 80,120),  when I  run inference.py,   we got some problems~~
however, if I try inference  image with much bigger size (e.g.360,480), everything works well.
So,  is there still any limits for the input image size?  can not support  for any image size?
