### ISSUE TITLE
how is the accuracy calculated?

### ISSUE THREAD

**Issue by niexhbruce** [hellochick/ICNet-tensorflow#30]
Hi,

Thanks so much for sharing the code. I just have a question about the accuracy (65.56/67.7) in the readme. Is the accuracy calculated as mIOU? Did you get this number from the model weights provided by the author or from the weights trained by yourself on the cityscapes data?

**Comment by hellochick** [comment]
Yes, that's accuracy calculated as mIoU. I get this number from the transformed weight which converted from the caffe model provided by the author.
