### ISSUE TITLE
a bug in the network structure for ICNet_BN

### ISSUE THREAD

**Issue by hitexcalibur** [hellochick/ICNet-tensorflow#41]
Hi,

Very nice work.

Seems that there's a small bug in the network structure for ICNet_BN. In line 320 in your model.py, it should be 'conv3_2_1x1_increase_bn' instead of 'conv3_2_1x1_increase'
and the same for line 385

**Comment by hellochick** [comment]
Hi,
thank you a lot! Maybe this bug can solve the problem which confused me long time!!! Really appreciate.
