### ISSUE TITLE
picture path in ade20k dataset seems not right

### ISSUE THREAD

**Issue by BeyondHeaven** [hellochick/ICNet-tensorflow#45]
when I put this command
`python evaluate.py --dataset=cityscapes --filter-scale=2 --model=others`
`ValueError: Failed to find file: /home/media/data/ade20k/images/validation/ADE_val_00000001.jpg`
but in fact the path is
(in folder "validation", there are several folders to arrange pictures in alphabetical order )

> [media@localhost validation]$ find . -name 'ADE_val_00000001.jpg'
> ./a/abbey/ADE_val_00000001.jpg

I download it on http://groups.csail.mit.edu/vision/datasets/ADE20K/ ,the full dataset(ADE20K_2016_07_26.zip)

After I copy all pictures in one folder , it shows

> ValueError: Failed to find file: /home/media/data/ade20k/annotations/validation/ADE_val_00000001.png

but this png file doesn't exist

Is this a bug or I did something wrong?

**Comment by hellochick** [comment]
Hey @BeyondHeaven, I use ADE20k dataset from this website [MIT Scene Parsing Benchmark](http://sceneparsing.csail.mit.edu/ ).

**Comment by BeyondHeaven** [comment]
@hellochick Thanks
But have you ever tested it? My result is extremely low

> [media@localhost test1]$ python evaluate.py --dataset=ade20k --filter-scale=2 --model=others
2018-02-27 14:28:49.945577: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
No checkpoint file found.
evaluation: 100%|███████████████████████████████████████████████████████████████████████| 2000/2000 [20:18<00:00,  1.64it/s]
mIoU: 0.00036441575503

**Comment by hellochick** [comment]
@BeyondHeaven , since you didn't load the checkpoint. If you get "No checkpoint file found" message, it means that you did not put the checkpoint in the correct position.

**Comment by BeyondHeaven** [comment]
@hellochick  But I have put all files into 'model' directory

```
[media@localhost ICNet-tensorflow]$ ls model
checkpoint.txt                           icnet_cityscapes_train_30k_bnnomerge.npy     icnet_cityscapes_trainval_90k.npy     model.ckpt-27150.meta
icnet_cityscapes_bnnomerge.prototxt.txt  icnet_cityscapes_train_30k.npy               model.ckpt-27150.data-00000-of-00001
icnet_cityscapes.prototxt.txt            icnet_cityscapes_trainval_90k_bnnomerge.npy  model.ckpt-27150.index
```

Anything wrong?

**Comment by hellochick** [comment]
@BeyondHeaven , can you try to delete the filename extension of checkpoint? Like this: `checkpoint.txt` -> `checkpoint`

**Comment by BeyondHeaven** [comment]
@hellochick  I've done it. Thanks a lot.
