### ISSUE TITLE
Increase in accuracy after fixing #41 ?

### ISSUE THREAD

**Issue by rydeldcosta** [hellochick/ICNet-tensorflow#49]
Hi @hellochick. After fixing the bug referenced in #41 , did you get a bump in accuracy too? The Trainval_bn model gives me around 80% class IoU. However I am not sure if there is some mistake.

**Comment by hellochick** [comment]
@rydeldcosta, yes! I think this bug resulted in the low accuracy, so after fixing it we got improvement in accuracy.

**Comment by rydeldcosta** [comment]
@hellochick did you record the results? If so, what accuracy did you get?

**Comment by hellochick** [comment]
@rydeldcosta, I get 81.06% mIoU, and I have put the results in README.md.

**Comment by rydeldcosta** [comment]
Thanks a lot!
