### ISSUE TITLE
Regarding Alpha Blending value 

### ISSUE THREAD

**Issue by SoebHussain** [hellochick/ICNet-tensorflow#56]
Hi 

Thank for sharing the code. I am trying to visualise the output as shown in this [video](https://youtu.be/qWl9idsCuLQ) . For that Alpha blending value is used in other repo. Could you help me with the changes required for this code.
Thanks again

**Comment by wzhouuu** [comment]
Not sure if you have fixed this problem. in inference.py line 182, you can save the `preds[0]+imgs[i]`, that worked for me without using Alpha.
