### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'img_mean' and 'coord'

### ISSUE THREAD

**Issue by npv0** [hellochick/ICNet-tensorflow#6]
I was trying to run evaluate.py with cityscapes dataset in the path as below in Windows 10 (Git Bash)
using Python 3.5.2 and tensorflow-gpu 1.3.0

I have modified data directory path with my local path  as below path

DATA_DIRECTORY = './data/cityscapes_dataset/cityscape'
(where I have copied cityscapes contents, leftImg8bit and gtFine folders)
changed  the path of SAVE_DIR = './output_new/'

But I could not excecute the evaluation script due to following error

npv0@LAPTOP-8FO36PI9 MINGW64 /e/Projects/DeepLearning/tf/ICNet-tensorflow (master)
$ **python evaluate.py --model=train --measure-time**
Namespace(flipped_eval=False, measure_time=True, model='train', save_dir='./output_new/')
Traceback (most recent call last):
  File "evaluate.py", line 153, in <module>
    main()
  File "evaluate.py", line 82, in main
    coord)
**TypeError: __init__() missing 2 required positional arguments: 'img_mean' and 'coord'**

I searched about the [issue](https://stackoverflow.com/questions/28122963/typeerror-init-missing-2-required-positional-arguments-client-socket-a) and it could be related to missing number of arguments to ImageReader

Even if at the line 72 has  coord = tf.train.Coordinator() , I was getting the above error.

The same is observed in Python 2.7 in windows and Python 3.5 in Ubuntu
Please have a look at this issue. Thanks

**Comment by hellochick** [comment]
Hey @npv0, Im sorry for that I have updated the wrong code. I have fixed it and it can work with evaluation now. Thanks.

**Comment by npv0** [comment]
Thanks for the fix @hellochick . Issue got resolved.

I have made a few changes locally to resolve few issues after checking out the latest [update

](https://github.com/hellochick/ICNet-tensorflow/commit/6cd4fbf34a8c1782b9de1f8e4c9e572a79d1f86b)

1. Changed Line 71 for param_name, data in data_dict[op_name].**iteritems():** to for param_name, data in data_dict[op_name].**items():**


Traceback (most recent call last):
  File "evaluate.py", line 155, in <module>
    main()
  File "evaluate.py", line 126, in main
    net.load(model_train30k, sess)
  File "E:\Projects\DeepLearning\tf\ICNet\ICNet-tensorflow\network.py", line 71, in load
    for param_name, data in data_dict[op_name].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'


2. I was getting issue as the cityscapes file names are difference in eval_list.txt for me.

npv0@LAPTOP-8FO36PI9 MINGW64 /e/Projects/DeepLearning/tf/ICNet/ICNet-tensorflow (master)
$ python3 evaluate.py --model=train
Namespace(flipped_eval=False, measure_time=False, model='train', save_dir='./output/')
Traceback (most recent call last):
  File "evaluate.py", line 155, in <module>
    main()
  File "evaluate.py", line 84, in main
    coord)
  File "E:\Projects\DeepLearning\tf\ICNet\ICNet-tensorflow\image_reader.py", line 107, in __init__
    self.image_list, self.label_list = read_labeled_image_list(self.data_dir, self.data_list)
  File "E:\Projects\DeepLearning\tf\ICNet\ICNet-tensorflow\image_reader.py", line 62, in read_labeled_image_list
    raise ValueError('Failed to find file: ' + mask)
ValueError: Failed to find file: ./data/cityscapes_dataset/cityscape\gtFine/val/lindau/lindau_000000_000019_gtFine_labelTrainIds.png

I have changed eval_list.txt file (renamed all gtFine_labelTrainIds to gtFine_labelIds) for eg: lindau_000000_000019_gtFine_labelTrainIds.png
to lindau_000000_000019_gtFine_labelIds.png

a
