### ISSUE TITLE
Any suggestions for low resolution images?

### ISSUE THREAD

**Issue by VincentGu11** [hellochick/ICNet-tensorflow#68]
Hi @hellochick, thanks for sharing the codes.

Recently I'm dealing with a problem which is a binary segmentation(target or not) task and requires extremely high speed (about 100fps required). One way to get that high speed is to shrink the input size of the image I think. I set my input image size to 640*360 and the network input to 360*360. However, the result seems not very good, the network doesn't learn much from the dataset. Have you done some experiment with this problem? Thanks a lot! :)

**Comment by hellochick** [comment]
Hey @VincentGu11 ,

Maybe you need to load some pre-trained model and keep fine-tuning on your own dataset. Or you can refer to #50. It seems that the issue can help you to solve binary segmentation task.
