### ISSUE TITLE
train.py: error: unrecognized arguments: --model=others

### ISSUE THREAD

**Issue by kecaiwu** [hellochick/ICNet-tensorflow#7]
why i can't find the parameters about the '--model'?

**Comment by hellochick** [comment]
Hey, sorry for that. It’s my typo. You can run the train.py without the Arg of —model.

**Comment by kecaiwu** [comment]
Thank for reply. And i have another question, why set the NUM_CLASSES=27 to NUM_CLASSES=19 in train.py? The cityscapes dataset have 27 classes?

**Comment by hellochick** [comment]
Hey @kecaiwu, Cityscapes have 19 classes. And I test on my own datasets which has 27 classes

**Comment by kecaiwu** [comment]
Thanks hellochick.
