### ISSUE TITLE
Test Speed

### ISSUE THREAD

**Issue by InstantWindy** [hellochick/ICNet-tensorflow#72]
I have a question,I don't know how to calculate the speed,how did you calculate the speed? thank you !

**Comment by hellochick** [comment]
Hey @InstantWindy,

To simplify the testing procedure, you can using `time` library, and following is the sample code:

```
start_time = time.time()

# The part which you want to calculate
output = sess.run(...)

end_time = time.time()

elapse_time = end_time - start_time
```

Or if you want to know the details of the execution time, you can use `tf.profiler` which provided in tf 1.8.
