### ISSUE TITLE
mIoU score of Cityscapes dataset is too low

### ISSUE THREAD

**Issue by Alex-Leipi** [hellochick/ICNet-tensorflow#73]
Hello,
I downloaded the Cityscapes dataset and provided pretrained Models according to the readme. When I run evaluate.py the mIoU scores are different to provided ones:
train: 67.26%
trainval: 80.90%
train_bn: 67.30%
trainval_bn: 80.80%

Does anyone else get the same results?

**Comment by hellochick** [comment]
Hey, 
According to my experience, the mIoU scores may be a little different due to different tensorflow version, but it will vary in a reasonable range.
