### ISSUE TITLE
Inference on ADE20K, output is different than those in repo

### ISSUE THREAD

**Issue by AliManUtd1993** [hellochick/ICNet-tensorflow#77]
Hi.

I downloaded the checkpoint files you provided on Google drive for ADE20K dataset, and using the following command on indoor_1.jpg, indoor_2.jpg, and outdoor_2.jpg, I got the following results.
`python inference.py --img-path=./input/outdoor_2.png --dataset=ade20k --filter-scale=2 --model=others
`

The problem is that they are not as accurate as the images in the output folder in the repository. May I ask the checkpoint files in the Google drive folder are updated or not? Or is there possible that something else went wrong?

(I am able to replicate your result on CityScapes dataset.)

![indoor_1](https://user-images.githubusercontent.com/11467351/45121582-6fed0000-b116-11e8-9a51-bce7ce1ce973.jpg)
![indoor_2](https://user-images.githubusercontent.com/11467351/45121583-6fed0000-b116-11e8-8965-21abe8dc4a6a.jpg)
![outdoor_2](https://user-images.githubusercontent.com/11467351/45121584-6fed0000-b116-11e8-8663-8d495c3fef06.png)

**Comment by hellochick** [comment]
Hey, 

I am not sure if the checkpoint is the same or not because there are several versions. I'm  sorry for that. But I think the checkpoints might be only a little different between each others. Recently, I am going to update the repo and checkpoints!
