### ISSUE TITLE
About RGB-BGR conversion in preprocess() in inference and evaluate

### ISSUE THREAD

**Issue by Sparkofska** [hellochick/ICNet-tensorflow#79]
Hi there,
I have a question concerning the preprocessing part in `evaluate.py` and `inference.py`:
The channels get swapped from _RGB_ to _BGR_, but I cannot find such a swapping in `train.py`. Why is it applied and did I miss it in `train.py`?

**Comment by hellochick** [comment]
Hey,
Since I used the image queue in training phase, which is different with inference and evaluation. You can find the pre-processing part in `image_reader.py`.

**Comment by Sparkofska** [comment]
Thanks for the quick reply. But I'm still wondering why a channel swapping (RGB to BGR conversion) is necessary?

**Comment by hellochick** [comment]
Since the pre-trained weight from original author is based on caffe, which use BGR color space. However, tensorflow read images using RGB color space.

**Comment by Sparkofska** [comment]
OK, simple answer, got it.
Thank you very much!
