### ISSUE TITLE
What's your output node of your model file ?help.

### ISSUE THREAD

**Issue by wangyarui** [hellochick/ICNet-tensorflow#8]
Hi, friends, I am a postgraduate at school. I am trying to transplant this model file to my android examples, I  added the following code in your `inference.py` to save your ckpt model file
`saver=tf.train.Saver()
saver.save(sess,'checkpoint/ICNet.ckpt')`
Then I adopt the 'CkptToPb.py' written by myself to transform the ckpt model to pb file.
But I need know your output node for your model, and I can not find something obviously  about your output node, I need your help .Can you update your **'model.ckpt'** to your git ? I really want to check it with mine to find what is wrong.
I am so appreciated your warm heart, thank you very much.
Thanks again sincerely.

**Comment by hellochick** [comment]
Hey, @wangyarui you can call `net.layers['conv6_cls']` to get the node. Btw, I have put the model.ckpt on the google drive. Is that helpful for you?

**Comment by wangyarui** [comment]
Hey, @hellochick thanks for your response. I downloaded your **model.ckpt** and transformed it to **ICNet.pb**. But when I was transforming it to **ICNet.pb**，when I set the **output node** **con6_cls**, the error dedicated that **conv6_cls** is not existed in this graph. Although I adopted **tensorboard** and I find the **conv6_cls**......I really do not know what happed, Now I am reading carefully your train.py code. Thanks again.

**Comment by hellochick** [comment]
Hey, @wangyarui. Sorry for my late reply. Have you solved your problem yet?

**Comment by wangyarui** [comment]
@hellochick yes，I have solve my problem,thank you very much.

**Comment by pewpewpeww** [comment]
Hi @wangyarui, may I know what is the output node you used in the end? I am also facing the same problem; trying to convert to .pb file and used conv6_cls as output node name but it does not work.

**Comment by chegnyanjun** [comment]
Hi, @pewpewpeww, I am also facing the same problem as you.Do you have solved?
