### ISSUE TITLE
Initial model to train

### ISSUE THREAD

**Issue by mattpfr** [hellochick/ICNet-tensorflow#82]
@hellochick Nice work with this ICNet implementation, I was curious to know if you could share the initial model you used to build the models you provide in the google drive links for cityscape. I tried to use the psp50 model that you provide for the PSPNet implementation, but it seems I cannot start from that checkpoint.
Thanks a lot!

**Comment by hellochick** [comment]
Hey,

If you want to use pspnet50 model as your intial model, you need to take care of the layer name between these two models. Also, pspnet50 model can only be used to restore the first branch of ICNet. 

Another important issue is that, pspsnet50 model is a non-pruned model, so you need to using `--filter-scale=2` to setup ICNet model. After doing these things, you can init your ICNet with pspnet50 model.

I recommend you that you can use the provided restore weight in google drive, it's the easiest way!

**Comment by mattpfr** [comment]
Thanks for the tips! I agree that using the provided restore weights is the easiest way, I just wanted to know exactly how to reach the accuracy that you report with your train.py script. Basically just reproducing your results ;)
I will try what you suggested and see where I can get :)
