### ISSUE TITLE
how to train my dataset from scratch?

### ISSUE THREAD

**Issue by zhangyunming** [hellochick/ICNet-tensorflow#84]
hi,nice work ！

when i train my dataset with your code from scratch, i modify the ''model_weight='./model/cityscapes/icnet_scapes_train_30k_bnnomerge.npy'''in train.py to
'model_weight = '' '   so i can run it with scratch, but the bug:
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
whats wrong with my operation？

because i can not download the pretrain model ,so i must use train with scratch

**Comment by zhangyunming** [comment]
solve it

**Comment by harora** [comment]
Hi Can you tell how you solved this?
