### ISSUE TITLE
in demo.py why I test  inference speed only 6 fps with  titan xp

### ISSUE THREAD

**Issue by zaibian** [hellochick/ICNet-tensorflow#88]
hi，in demo.py why I test  inference speed only 6 fps with  titan xp？

**Comment by hellochick** [comment]
Could you please check your tensorflow version? Maybe you are using tensorflow instead of tensorflow-gpu, that is, you are not using gpu to accelerate.

**Comment by hellochick** [comment]
You can follow the instruction in `demo.ipynb`, and change `cv2.imread` into opencv VideoCapture to get input frames, something like this:

```python
cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # predict output
    output = net.predict(frame)

    cv2.imshow('frame', output)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

**Comment by zaibian** [comment]
thanks
