### ISSUE TITLE
Can not download pre-trained weights

### ISSUE THREAD

**Issue by Aaron9477** [hellochick/ICNet-tensorflow#96]
hi,hellochick:
Thanks for your great work!
I want to download the pre-trained weights using your command line:
`python script/download_weights.py --dataset cityscapes`
But I can not download it with this wrong:
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=15S_vZoZZwBsORxtRAMcbdsI99o6Cvo5x (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdba179a7d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`
I can browse Google and Youtobe. Is the download link invalid? Or may I have some wrong operation?
look forward to your reply
good wish!

**Comment by hellochick** [comment]
You can download the pretrained model here using [Google drive](https://drive.google.com/open?id=1pBN07IW_zxEVlL2q9ColGs6QkUNkplsi).

**Comment by Aaron9477** [comment]
> You can download the pretrained model here using [Google drive](https://drive.google.com/open?id=1pBN07IW_zxEVlL2q9ColGs6QkUNkplsi).

I have downloaded the pre-trained network! Thanks a lot!
best wishes!
