### ISSUE TITLE
params of train.py has error,--update-mean-var and update_mean_var.I think it is the reason of bad result

### ISSUE THREAD

**Issue by kasyoukin** [hellochick/ICNet-tensorflow#97]
https://github.com/hellochick/ICNet-tensorflow/blob/a8f0eba4b40e60b7c198f96a780bf7448be67841/train.py#L24

https://github.com/hellochick/ICNet-tensorflow/blob/a8f0eba4b40e60b7c198f96a780bf7448be67841/train.py#L133

**Comment by hellochick** [comment]
Hey, I think this is not error, if you set the flag --update-mean-var, args.update_mean_var will be set to True. You can try to print sth in that if statement.
